#!/bin/bash

source ./commonscript
app_name=catalogue

check_root
app_setup
nodejs_setup
systemd_setup


cp $SCRIPT_DIR/mongo.repo /etc/yum.repos.d/mongo.repo 
dnf install mongodb-mongosh -y &>>$LOG_FILE
VALIDATE $? "Installing MongoDB Client"

STATUS=$(mongosh --host mongodb.anjuma.store --eval 'db.getMongo().getDBNames().indexOf("catalogue")') # make sure your mongodb record name is given her
if [ $STATUS -lt 0 ]
then
    mongosh --host mongodb.anjuma.store </app/db/master-data.js &>>$LOG_FILE # make sure your mongodb record name is given here
    VALIDATE $? "Loading data into MongoDB"
else
    echo -e "Data is already loaded ... $Y SKIPPING $N"
fi

print_time