#!/bin/bash

source ./commonscript

SCRIPT_DIR=$PWD

check_root

dnf module disable nginx -y &>>$LOG_FILE
VALIDATE $? "Disabling Default Nginx"

dnf module enable nginx:1.24 -y &>>$LOG_FILE
VALIDATE $? "Enabling Nginx:1.24"

dnf install nginx -y &>>$LOG_FILE
VALIDATE $? "Installing Nginx"

rm -rf /usr/share/nginx/html/* &>>$LOG_FILE
VALIDATE $? "Removing default content"

curl -o /tmp/frontend.zip https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip &>>$LOG_FILE
VALIDATE $? "Downloading frontend"

cd /usr/share/nginx/html
unzip /tmp/frontend.zip &>>$LOG_FILE
VALIDATE $? "Unzipping frontend"

rm -f /etc/nginx/nginx.conf &>>$LOG_FILE
VALIDATE $? "Removing default nginx.conf"

# if [ ! -f "$SCRIPT_DIR/nginx.conf" ]; then
#   echo -e "$R nginx.conf NOT FOUND in $SCRIPT_DIR. Exiting. $N" | tee -a $LOG_FILE
#   exit 1
# fi

cp "$SCRIPT_DIR/nginx.conf" /etc/nginx/nginx.conf &>>$LOG_FILE
VALIDATE $? "Copying nginx.conf"


systemctl enable nginx &>>$LOG_FILE
systemctl restart nginx &>>$LOG_FILE
VALIDATE $? "Restarting nginx"

print_time
